package br.terna.inter.v2.boleto.emissao;

public enum CodigoDesconto {
    NAOTEMDESCONTO, VALORFIXODATAINFORMADA, PERCENTUALDATAINFORMADA, VALORANTECIPACAODIACORRIDO, VALORANTECIPACAODIAUTIL, PERCENTUALVALORNOMINALDIACORRIDO, PERCENTUALVALORNOMINALDIAUTIL
}
